/* Separate team layout and state. No ceremony controller or card geometry. */
(()=>{'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const rank={mythic:0,legendary:1,epic:2,rare:3,common:3}, labels=['神話','神話＋傳說','神話＋傳說＋史詩','全隊'],limits=[2,6,12,20], symbols=['◆◆','◆','◇','△'];
const cards=TEAM_DATA.cards, byId=new Map(cards.map(c=>[c.id,c]));
const initial=cards.filter(c=>c.rarity!=='mythic'||cards.filter(x=>x.rarity==='mythic').indexOf(c)<2).filter(c=>c.rarity!=='legendary'||cards.filter(x=>x.rarity==='legendary').indexOf(c)<4).map(c=>c.id);
let roster=[...initial],skills=[null,null,null,null],selected=roster[0],face=null, generation=0,pending=null,pickerMode='add',skillSlot=0,previewTimer=0;
const state={preview:null,lastReject:null,previewElapsed:null};
const screen=$('#team-screen');
function counts(ids){return limits.map((_,i)=>ids.filter(id=>rank[byId.get(id).rarity]<=i).length)}
function violations(ids){return counts(ids).flatMap((n,i)=>n>limits[i]?[i]:[])}
function clearOperation(){clearTimeout(previewTimer);state.preview=null;state.lastReject=null;$('#capacity-errors').textContent='';$$('.capacity-row').forEach(e=>e.classList.remove('affected','violated'));screen.getAnimations({subtree:true}).forEach(a=>a.cancel())}
function proxy(c,index,handler){const b=document.createElement('button');b.className='team-proxy';b.dataset.id=c.id;b.setAttribute('aria-label',`${index===null?'候選':String(index+1).padStart(2,'0')} ${c.name} ${HoloCardFace.LABEL[c.rarity]}`);b.innerHTML=`<span class="proxy-image"><img src="${TEAM_DATA.images[c.proxy]}" alt="" draggable="false">${index===null?'':`<span class="proxy-index team-marker">${String(index+1).padStart(2,'0')}</span>`}<span class="proxy-symbol">${symbols[rank[c.rarity]]}</span></span><span class="proxy-name">${c.name}</span>`;b.onclick=handler;return b}
function renderCapacity(){const n=counts(roster);$('#capacity-rows').innerHTML=labels.map((l,i)=>`<div class="capacity-row" data-row="${i}"><span>${l}</span><span class="digits">${n[i]} / ${limits[i]}</span><span class="segments" style="--count:${limits[i]}" aria-hidden="true">${Array.from({length:limits[i]},(_,j)=>`<i class="${j<n[i]?'filled':''}"></i>`).join('')}</span></div>`).join('')}
function renderRoster(){const grid=$('#team-grid');grid.replaceChildren(...roster.map((id,i)=>{const b=proxy(byId.get(id),i,()=>select(id,true));b.setAttribute('aria-selected',String(id===selected));return b}));$('#roster-count').textContent=`${roster.length} / 20`;renderCapacity();renderSkills()}
function disposeFace(){if(face){HoloCardFace.unobserve(face);face.remove();face=null}}
const shadow=$('#card-host').attachShadow({mode:'open'});const style=document.createElement('style');style.textContent=TEAM_DATA.css;shadow.append(style);
$('#card-host').style.setProperty('--frame-mask',`url("${TEAM_DATA.masks.frame}")`);$('#card-host').style.setProperty('--glitter-mask',`url("${TEAM_DATA.masks.glitter}")`);
function detail(){disposeFace();const c=byId.get(selected)||byId.get(roster[0]);if(!c){$('#detail-name').textContent='尚未編入';$('#detail-number').textContent='—';$('#detail-operation').textContent='選擇成員以編入';return}selected=c.id;const index=roster.indexOf(c.id),serial=index>=0?String(index+1).padStart(2,'0'):'候選';
$('#detail-number').textContent=serial;$('#detail-name').textContent=c.name;$('#detail-rarity').textContent=HoloCardFace.LABEL[c.rarity];$('#detail-operation').innerHTML=`<span class="selection-serial">${serial}</span> · ${index>=0?'已編入':'尚未編入'} · ${c.name}`;$('#team-detail').dataset.id=c.id;$('#team-detail').dataset.slot=serial;
face=HoloCardFace.create(c,{masks:TEAM_DATA.masks,resolve:n=>TEAM_DATA.images[n]});shadow.append(face);HoloCardFace.observe(face);HoloCardFace.refit(face);$$('#team-grid .team-proxy').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.id===selected)));}
function select(id,open=false){if(!byId.has(id))return;clearOperation();selected=id;detail();if(open){screen.classList.add('detail-open');if(innerWidth<=700)$('#detail-close').focus()}}
function pose(x,y){if(face&&document.body.dataset.screen==='team')HoloCardFace.paint(face,byId.get(selected).rarity,x,y,{tilt:!matchMedia('(prefers-reduced-motion: reduce)').matches})}
$('#card-host').addEventListener('pointermove',e=>{const r=$('#card-host').getBoundingClientRect();pose(Math.max(-1,Math.min(1,(e.clientX-r.left)/r.width*2-1)),Math.max(-1,Math.min(1,(e.clientY-r.top)/r.height*2-1)))});
$('#card-host').addEventListener('pointerleave',()=>pose(0,0));$('#card-host').addEventListener('keydown',e=>{const p={ArrowLeft:[-.6,0],ArrowRight:[.6,0],ArrowUp:[0,-.6],ArrowDown:[0,.6],Escape:[0,0]}[e.key];if(p){e.preventDefault();pose(...p)}});
function preview(id){clearOperation();pending=id;const c=byId.get(id),start=performance.now(),token=generation;previewTimer=setTimeout(()=>{if(token!==generation||!c)return;state.preview=limits.map((_,i)=>rank[c.rarity]<=i);state.previewElapsed=performance.now()-start;$$('.capacity-row').forEach((e,i)=>e.classList.toggle('affected',state.preview[i]));$('#picker-status').textContent=`${c.name} · 影響：${labels.filter((_,i)=>state.preview[i]).join('、')}`},120)}
function add(id,replace=null,origin=null){clearOperation();if(!byId.has(id))return false;let next=roster.filter(x=>x!==replace);if(next.includes(id)){$('#picker-status').textContent='此成員已在隊伍中';return false}next.push(id);const bad=violations(next);if(bad.length){const n=counts(roster),after=counts(next);state.lastReject={id,rows:bad,before:[...roster],after:next};$('#capacity-errors').textContent=bad.map(i=>`${labels[i]}合計已達 ${n[i]}，加入後將為 ${after[i]}`).join('；');$('#picker-status').textContent=$('#capacity-errors').textContent;bad.forEach(i=>{const e=$$('.capacity-row')[i];e.classList.add('violated');const a=e.animate([{borderColor:'#bcc3b3'},{borderColor:'#bcc3b3'}],{duration:300});a.id='team-over-limit'});const target=origin||$(`#picker-grid [data-id="${id}"]`)||$('#add-member');const a=target.animate([{transform:'translateY(-12px)'},{transform:'translateY(0)'}],{duration:210,easing:'ease-out'});a.id='team-return';return false}if(replace){next=roster.map(x=>x===replace?id:x)}roster=next;selected=id;renderRoster();detail();return true}
function remove(){clearOperation();roster=roster.filter(id=>id!==selected);selected=roster[0];renderRoster();detail();screen.classList.remove('detail-open')}
function renderSkills(){$('#skill-grid').replaceChildren(...skills.map((id,i)=>{const b=document.createElement('button');b.className='skill-slot';b.innerHTML=`<small>獨立技能 ${i+1}</small>${id?byId.get(id).name:'＋ 挑選'}`;b.onclick=()=>openPicker('skill',i);return b}))}
function assignSkill(i,id){if(!byId.has(id)||i<0||i>3)return false;if(byId.get(id).rarity==='mythic'&&skills.some((x,j)=>j!==i&&x&&byId.get(x).rarity==='mythic')){$('#picker-status').textContent='神話技能最多 1 張；請先替換原神話技能';return false}skills[i]=id;renderSkills();return true}
function openPicker(mode,slot=0){clearOperation();pending=null;pickerMode=mode;skillSlot=slot;$('#picker-title').textContent=mode==='skill'?'挑選獨立技能':mode==='replace'?'替換目前成員':'新增隊伍成員';$('#picker-status').textContent=mode==='skill'?'來源尚未定案 · 此處僅配置技能格':'選擇成員，預覽受影響的累加上限';$('#picker-confirm').disabled=true;$('#picker-grid').replaceChildren(...cards.map(c=>{const b=proxy(c,null,()=>{if(mode==='skill'){pending=c.id;$('#picker-status').textContent=`獨立技能 · ${c.name}`}else preview(c.id);$('#picker-confirm').disabled=false;$$('#picker-grid button').forEach(x=>x.setAttribute('aria-selected',String(x===b)))});if(mode!=='skill'&&roster.includes(c.id))b.disabled=true;return b}));$('#team-picker').showModal()}
function closePicker(){clearTimeout(previewTimer);pending=null;$('#team-picker').close()}
$('#picker-confirm').onclick=()=>{if(!pending)return;const ok=pickerMode==='skill'?assignSkill(skillSlot,pending):add(pending,pickerMode==='replace'?selected:null);if(ok)closePicker()};
$('#picker-close').onclick=closePicker;$('#team-picker').addEventListener('cancel',closePicker);
$('#add-member').onclick=()=>openPicker('add');$('#replace-member').onclick=()=>openPicker('replace');$('#remove-member').onclick=remove;
$('#detail-close').onclick=()=>{screen.classList.remove('detail-open');$(`#team-grid [data-id="${selected}"]`)?.focus()};
function setScreen(name){if(!['map','team'].includes(name))return false;generation++;if(name==='team')map20.cancel();clearOperation();closePicker();disposeFace();document.body.dataset.screen=name;screen.classList.remove('detail-open');if(name==='team'){renderRoster();detail()}else{lines();terrainLayout()}return true}
$('#open-team').onclick=()=>setScreen('team');$('#return-map').onclick=()=>setScreen('map');
window.team20={cards,counts,violations,add,select,preview,assignSkill,pose,setScreen,openPicker,get roster(){return [...roster]},get skills(){return [...skills]},get face(){return face},get state(){return {...state}},get generation(){return generation},reset(){clearOperation();roster=[...initial];skills=[null,null,null,null];selected=roster[0];renderRoster();detail()},ablate(flags=[]){for(const name of ['carrier','texture','selection'])screen.classList.toggle('no-team-'+name,flags.includes(name))}};
document.body.dataset.screen='map';if(new URLSearchParams(location.search).get('screen')==='team')setScreen('team');
})();
